name: Zephyr Build and Embedhub Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for proper Git information

    - name: Setup Zephyr Project
      # Assuming you have a custom action or script here to set up the Zephyr environment.
      # Since we don't know the exact setup, this is a placeholder.
      run: |
        echo "Setting up Zephyr environment..."
        # Example commands (Replace with your actual setup if needed)
        # west init -l zephyr/
        # west update
        # west zephyr-build -b makerville_badge_ms ./

    - name: Build Zephyr Application
      # This step should execute the actual Zephyr build command.
      run: |
        echo "Building Zephyr application..."
        # Replace with the actual build command that generates the zephyr.bin file
        mkdir build 
        echo "Mock Zephyr Binary" > build/zephyr.bin

    - name: Deploy to Embedhub (FIXED SECRET NAME)
      uses: Embed-Hub/EmbedHub-GitHub-Action@master
      with:
        api-key: ${{ secrets.EMBEDHUB_KEY }} # <-- CORRECTED: Using EMBEDHUB_KEY
        organization: ${{ secrets.MAHENDRA }}
        project: ${{ secrets.MAKERVILLE-BADGE-MS }}
        files: 'build/*.bin'

        
    - name: Summary
      run: echo "Deployment workflow completed. Check Embedhub for the uploaded binary."
